# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: Bike
google_analytics: Bike
title: Bike

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Bike

description: Stylish Jekyll Theme
author:
  name: Bike
  email: admin@cctvhk.net
  github: bike-py
  twitter: bike
  pinterest: asd123
  linkedin: asd123
  bio: 做人不要太攀比、踏踏实实做自己。
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
